name: ppqm_interactive
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.11
  - ipywidgets
  - jupyter
  - jupyterlab
  - jupytext
  - matplotlib
  - mopac
  - mypy
  - networkx
  - nglview
  - numpy
  - pandas
  - pip
  - pre-commit
  - pytest
  - pytest-cov
  - rdkit
  - rmsd
  - scipy
  - tqdm
  - xtb
